language: node_js
node_js:
  - "10.0"

env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

before_script:
  - yarn build

after_success:
  - ./.travis_publish
